[package]
name = "add-numbers"
version = "1.0.0"
edition = "2021"
description = "Solana Smart Contract for adding numbers"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.17.0"

[lib]
crate-type = ["cdylib", "lib"]
